### ISSUE TITLE
[Production-Ready] The actuator Endpoints of Dubbo

### ISSUE THREAD

**Issue by mercyblitz** [dubbo/dubbo-spring-boot-project#1]
Dubbo `Properties` Endpoint : `/dubbo/properties`

Dubbo `ServiceBean` Endpoint : `/dubbo/services`

Dubbo `ReferenceBean` Endpoint : `/dubbo/references`

Dubbo `*Config` Endpoint : `/dubbo/configs`

Dubbo `Shutdown` Endpoint `/dubbo/shutdown`

**Comment by zhangruhong** [comment]
火钳刘明（Leave a message/comment before it becomes a top/hot tweet.）
