### ISSUE TITLE
关于使用注解的一点建议？

### ISSUE THREAD

**Issue by 709889989** [dubbo/dubbo-spring-boot-project#11]
@Service(
        version = "1.0.0",
        application = "${dubbo.application.id}",
        protocol = "${dubbo.protocol.id}",
        registry = "${dubbo.registry.id}"
)
@Reference(version = "1.0.0",
            application = "${dubbo.application.id}",
            url = "dubbo://localhost:12345")

感觉每次都要这样拷一份里边配置信息好多余，以后改的时候还要一个个的修改。

url = "dubbo://localhost:12345"  这个配置和服务治理Eureka 之类的结合下会更方便管理。

**Comment by mercyblitz** [comment]
You can remove 
application = "${dubbo.application.id}",
protocol = "${dubbo.protocol.id}",
registry = "${dubbo.registry.id}",

just leave url = "dubbo://localhost:12345", however, Dubbo supports specified application and others.
