### ISSUE TITLE
dubbo.registry.address = zookeeper://127.0.0.1:2181  少jar

### ISSUE THREAD

**Issue by peterm10g** [dubbo/dubbo-spring-boot-project#13]
java.lang.NoClassDefFoundError: org/I0Itec/zkclient/IZkStateListener
	at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperTransporter.connect(ZkclientZookeeperTransporter.java:26) ~[dubbo-2.5.9.jar:2.0.1]
	at com.alibaba.dubbo.remoting.zookeeper.ZookeeperTransporter$Adaptive.connect(ZookeeperTransporter$Adaptive.java) ~[dubbo-2.5.9.jar:2.0.1]
修改 dubbo.registry.address = zookeeper://127.0.0.1:2181（我本地的zk）  会出现  
确实少jar包

**Comment by lovepoem** [comment]
Now is dubbo-2.5.9.jar has not been released yet。

**Comment by peterm10g** [comment]
我自己编译的   这个与 dubbo2.5.9 没有关系吧

**Comment by qct** [comment]
In fact, duboo has very few dependencies as default, see [dependencies](http://dubbo.io/books/dubbo-user-book/dependencies.html).

As zookeeper registry is an optional registry implementation among Multicast, zookeeper, Redis, Simple, if you wanna use zookeeper as your registry, you should as dependency by yourself.

Currently dubbo supports two zookeeper client: zkclient and curator , you need to add one of them to your `pom.xml`, see [zookeeper](http://dubbo.io/books/dubbo-user-book/references/registry/zookeeper.html).

* zkclient 
```
<dependency>
  <groupId>com.101tec</groupId>
  <artifactId>zkclient</artifactId>
</dependency>
```

* curator 
```
<dependency>
    <groupId>com.netflix.curator</groupId>
    <artifactId>curator-framework</artifactId>
</dependency>
```

At last, if use curator, don't forget to add `dubbo.registry.client=curator` to your `application.properties`

**Comment by mercyblitz** [comment]
```xml
<dependency>
    <groupId>com.netflix.curator</groupId>
    <artifactId>curator-framework</artifactId>
</dependency>
```
as a implied dependencies
