### ISSUE TITLE
qos-server  端口 

### ISSUE THREAD

**Issue by peterm10g** [dubbo/dubbo-spring-boot-project#14]
dubbo.application.qos-port=33333
dubbo.application.qos-enable=false
这个配置并没有设置qos port  ？

dubbo.application.qos.port=33333
dubbo.application.qos.enable=false    这样配置  ok

**Comment by chickenlj** [comment]
I'm sorry, you are right, `dubbo.application.qos.port=33333` is the right way to go. 
The IDEA automatic completion has misled me, @mercyblitz will do some work to avoid confusion.
