### ISSUE TITLE
com.alibaba:dubbo-demo-api:jar:2.5.9 这个jar包没有

### ISSUE THREAD

**Issue by fendo8888** [dubbo/dubbo-spring-boot-project#15]
在dubbo-spring-boot-samples中com.alibaba:dubbo-demo-api:jar:2.5.9 这个jar包没有

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/blob/2.5.x/dubbo-demo/dubbo-demo-api/pom.xml

```
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.alibaba</groupId>
        <artifactId>dubbo-demo</artifactId>
        <version>2.5.9</version>
    </parent>
    <artifactId>dubbo-demo-api</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>The demo module of dubbo project</description>
    <properties>
        <skip_maven_deploy>true</skip_maven_deploy>
    </properties>
</project>
```

看代码是没有发布到maven

**Comment by fendo8888** [comment]
OK

**Comment by chickenlj** [comment]
@mercyblitz  At present, `dubbo-demo-api` will not be published to central repository, i think the demo project should avoid depend on this module.

**Comment by tateecredit** [comment]
[ERROR] Failed to execute goal on project dubbo-spring-boot-actuator: Could not resolve dependencies for project com.alibaba.boot:dubbo-spring-boot-actuator:jar:1.0.0-SNAPSHOT: Failure to find com.alibaba:dubbo-demo-api:jar:2.5.9 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by fendo8888** [comment]
我这里写了篇博客: [](http://blog.csdn.net/u011781521/article/details/79160999)

**Comment by lovepoem** [comment]
![image](https://user-images.githubusercontent.com/827112/35421282-41a6255c-027d-11e8-8a5a-48f2fd8ad43d.png)
dubbo-spring-boot-project/dubbo-spring-boot-actuator/pom.xml
```
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo-demo-api</artifactId>
            <version>${dubbo.version}</version>
            <scope>test</scope>
        </dependency>

```
@mercyblitz the problem still exists

**Comment by mercyblitz** [comment]
Please Retry

**Comment by lovepoem** [comment]
It's ok now

**Comment by neesonqk** [comment]
@lovepoem what font are you using for your terminal?
