### ISSUE TITLE
问下2.5.9版本添加了从上下文中获取代理bean的功能了吗？

### ISSUE THREAD

**Issue by Comven** [dubbo/dubbo-spring-boot-project#17]
之前交流过dubbo支持增加了例如spring的applicationContext.getBean(String beanName)这样的功能，可以支持通过名称获取接口代理实例Bean。 不知道本次版本是否支持了？

**Comment by mercyblitz** [comment]
`ReferenceBean` is still not a Spring Bean, You can get them from `ReferenceAnnotationBeanPostProcessor#getReferenceBeans()`.
PS: `ReferenceAnnotationBeanPostProcessor`  as a Spring Bean with name "referenceAnnotationBeanPostProcessor"
