### ISSUE TITLE
dubbo 2.5.9

### ISSUE THREAD

**Issue by peterm10g** [dubbo/dubbo-spring-boot-project#2]
dubbo 2.5.8 之后就是dubbo 2.6.0吧，这个2.5.9 是怎么回事？

**Comment by mercyblitz** [comment]
2.5.9 will release soon

**Comment by wujunshen** [comment]
when to release 2.5.9?I met maven build problem and it tell me no 2.5.9 version dubbo

**Comment by mercyblitz** [comment]
Dubbo 2.5.9 has been released!
