### ISSUE TITLE
示例怎么运行测试看到效果？

### ISSUE THREAD

**Issue by fengme** [dubbo/dubbo-spring-boot-project#23]

**Comment by mercyblitz** [comment]
http://localhost:8080/sayHello?name=Hello,World

**Comment by mercyblitz** [comment]
I will update document

**Comment by fengme** [comment]
so quickly, I did not notice your param in the method sayHello

**Comment by fengme** [comment]
How to check dubbo's admin console?
that web admin ui, you know, thx

**Comment by mercyblitz** [comment]
Dubbo's services will be discovered by admin console after being exported, thus works as before. :D
