### ISSUE TITLE
[suggestion]dubbo-spring-boot-starter add spring-boot-actuator dependency 

### ISSUE THREAD

**Issue by durcframework** [dubbo/dubbo-spring-boot-project#26]
Now the provider and consumer both depend spring-boot-actuator in pom.xml.
Maybe dubbo-spring-boot-starter add spring-boot-actuator dependency 
```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-actuator</artifactId>
        </dependency>
```

then provider or consumer use dubbo-spring-boot-starter only.

**Comment by mercyblitz** [comment]
Since the compatibility of Spring Boot is not well , It should not be implied dependencies, it'd better to add `spring-boot-*` dependencies by application.
