### ISSUE TITLE
duplicate slf4j in spring-boot-starter and dubbo starter

### ISSUE THREAD

**Issue by durcframework** [dubbo/dubbo-spring-boot-project#27]
spring-boot-starter depend log4j-over-slf4j.jar

dubbo starter depend zookeeper depend slf4j-log4j12.jar

It caused an error:

Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path, preempting StackOverflowError.

**Comment by mercyblitz** [comment]
Thank you for report.
