### ISSUE TITLE
dubbo-spring-boot-project中springboot的版本太低了，跟2.0.0的不兼容

### ISSUE THREAD

**Issue by gaoshili** [dubbo/dubbo-spring-boot-project#31]
from springboot version 2.0.0 after there is a big update,I hope that dubbo can be combined with the latest version, now I modify the source code 1.3.0 changed to 2.0.0 inside, but deleted some monitoring code inside,there will be a problem?

**Comment by mercyblitz** [comment]
The auto-configure is compatible with Spring Boot 2.0.0 , Dubbo starter may provide two versions for Spring Boot 1.x and 2.x

**Comment by qct** [comment]
> The auto-configure is compatible with Spring Boot 2.0.0 , Dubbo starter may provide two versions for Spring Boot 1.x and 2.x

Totally agree.  We need two branch to keep track with spring boot, like 1.x and 2.x, besides, I also think we should update the versions of dependency very often. 

Since spring boot 2.0.0.RC1 has been released today, maybe it's time to start Dubbo spring starter 2.0.0.
