### ISSUE TITLE
为什么provier 也引入spring-boot-web

### ISSUE THREAD

**Issue by maomaozhou** [dubbo/dubbo-spring-boot-project#34]
provier为什么要引入web，不太懂。

**Comment by mercyblitz** [comment]
to demonstrate mvc endpoints

**Comment by fachilles** [comment]
If you did add the srping-boot-web dependency, then there would be a web site in port 8080 (as http://localhost:8080). But that‘s not what we want. Just register a service in the right zk. 

How to resolve this with no srping-boot-web?
