### ISSUE TITLE
dubbo-starter启动后立即关闭

### ISSUE THREAD

**Issue by yufeng629** [dubbo/dubbo-spring-boot-project#35]
正如作者在 #33 中回答的那样， spring-boot-starter-actuator已经作为了可选项，但是对于spring-boot-starter-web，如果我在项目中不引入此依赖，或者我在应用的入口程序main方法里面设置web为false（即：new SpringApplicationBuilder(MyApplication.class).web(false).run(args);）会出现dubbo启动后又立即关闭的情况，也没有报出其他任何异常
![image](https://user-images.githubusercontent.com/15260012/35800044-a8605b64-0aa2-11e8-9d73-70465c2b6f93.png)

**Comment by mercyblitz** [comment]
Non-Web Spring Boot Application is not blocked on bootstrap
