### ISSUE TITLE
DubboMvcEndpoint 

### ISSUE THREAD

**Issue by peterm10g** [dubbo/dubbo-spring-boot-project#4]
public class DubboMvcEndpoint extends EndpointMvcAdapter......
      .......
 // Reference Beans
     ReferenceAnnotationBeanPostProcessor beanPostProcessor = getReferenceAnnotationBeanPostProcessor();
        int referencesCount = beanPostProcessor.getReferenceBeans().size();

beanPostProcessor.getReferenceBeans() 这个方法只有dubbo2.5.9 有吗？
我看加载了dubbo2.5.8 ，  dubbo 2.6.0 都没有。

**Comment by mercyblitz** [comment]
Retry!
