### ISSUE TITLE
pom引入dubbo-spring-boot-starter问题

### ISSUE THREAD

**Issue by Ln-guolin** [dubbo/dubbo-spring-boot-project#45]
pom引入配置：
`
<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
`
结果jar包无法下载，然后按照文档再添加以下配置之后，任然无法下载
`
<repositories>
		<repository>
			<id>sonatype-nexus-snapshots</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
`

下载之后的列表始终缺少jar，每次reimport之后文件列表如下：

com\alibaba\boot\dubbo-spring-boot-starter\1.0.0-SNAPSHOT\
        dubbo-spring-boot-starter-1.0.0-SNAPSHOT.jar.lastUpdated
        dubbo-spring-boot-starter-1.0.0-SNAPSHOT.pom.lastUpdated
        resolver-status.properties

**Comment by mercyblitz** [comment]
Please wait for release
