### ISSUE TITLE
引用这个starter，dubbo-admin怎么连接

### ISSUE THREAD

**Issue by Ln-guolin** [dubbo/dubbo-spring-boot-project#46]
请问一下，引用这个starter，要怎么填写dubbo-admin里面的：
`dubbo.registry.address=zookeeper://127.0.0.1:2181
dubbo.admin.root.password=root
dubbo.admin.guest.password=guest`

**Comment by huanzhang** [comment]
dubbo-admin总是看不到用这个starter启动的consumer，如何破？

**Comment by huanzhang** [comment]
在consumer里面，使用@Reference时候，把url去掉，就可以了

**Comment by mercyblitz** [comment]
If an issue exists , please reopen it
