### ISSUE TITLE
Spring Boot版本也太低了吧

### ISSUE THREAD

**Issue by ameizi** [dubbo/dubbo-spring-boot-project#5]
spring boot 1.3.0.RELEASE这也太低了吧

**Comment by peterm10g** [comment]
spring boot的版本我自己选着的1.5.8  也是可以的

**Comment by mercyblitz** [comment]
As middleware , more compatible more better , Dubbo Spring Boot will import indirectly dependecies of Spring Boot , The client can choose which one that you want.
