### ISSUE TITLE
升级到dubbo2.6.0 报错

### ISSUE THREAD

**Issue by peterm10g** [dubbo/dubbo-spring-boot-project#55]
dubbo-spring-boot-actuator/src/main/java/com/alibaba/boot/dubbo/actuate/endpoint/mvc/DubboMvcEndpoint.java:找不到符号。
dubbo2.6.1 合并了 2.5.9 和 2.6.0 ？  是这样吗  ？

**Comment by mercyblitz** [comment]
Please use dubbo2.6.1 in future or 2.5.9
