### ISSUE TITLE
大概计划什么时候推送到 Maven Repository

### ISSUE THREAD

**Issue by FreezeSoul** [dubbo/dubbo-spring-boot-project#6]
rt

**Comment by mercyblitz** [comment]
Depends on alibaba internal test on production

**Comment by mercyblitz** [comment]
It should be released with Dubbo `2.5.9`

**Comment by chickenlj** [comment]
The dubbo 2.5.9 has released.

**Comment by zhangruhong** [comment]
The dubbo 2.5.9 has released.  What is the release plan for this project?

**Comment by mercyblitz** [comment]
Plan to release at 2018.01.28

**Comment by luffyke** [comment]
when publish v1.0 release version?
