### ISSUE TITLE
DubboMvcEndpoint类中使用了未定义的方法

### ISSUE THREAD

**Issue by Jason-HuHu** [dubbo/dubbo-spring-boot-project#8]
DubboMvcEndpoint类中使用ReferenceAnnotationBeanPostProcessor的getReferenceBeans()方法，但是Dubbo中的ReferenceAnnotationBeanPostProcessor类中没有这个方法，因为没有Dubbo2.5.9，我使用的是Dubbo2.6.0

**Comment by suclogger** [comment]
As @mercyblitz mentioned in #6 , it should be released with Dubbo 2.5.9.

**Comment by mercyblitz** [comment]
@suclogger thank you ! :D

**Comment by Jason-HuHu** [comment]
@suclogger ok,thks!

**Comment by mercyblitz** [comment]
Dubbo 2.5.9 has been released!
