### ISSUE TITLE
编译能通过么？ 

### ISSUE THREAD

**Issue by wenjies** [dubbo/dubbo-spring-boot-project#9]
1、dubbo-demo-api   依赖找不到呀 。
2、2.5.9 找不到 改为2.60后 DubboMvcEndpoint类中使用了未定义的方法。
-------------------------------------------------------------------------------------
啥时候可以推到 Maven Repository哟

**Comment by mercyblitz** [comment]
Dubbo 2.5.9 will be released today or tomorrow

**Comment by rick-liao** [comment]
2.5.9今天什么时候发布呀？

**Comment by mercyblitz** [comment]
Dubbo 2.5.9 has been released!
